### ISSUE TITLE
Install habpanel as bundle

### ISSUE THREAD

**Issue by kirantpatil** [maggu2810/smarthome-packaging-sample-karaf#2]
Hi @maggu2810,

I would like to install [habpanel](https://github.com/openhab/org.openhab.ui.habpanel) as bundle.

What is the method to install it ?

Thanks.

**Comment by maggu2810** [comment]
Hi @kirantpatil,
I don't like to be harsh, but this is a issue tracker and for bugs.
Please don't use it for support requests.

If you need support how to install bundles or feature (or what is a Karaf feature) in the Karaf container, please have a look at the documentation of Karaf.
If you need support for the HABpanel, please use the support of that bundle.

Have a look at the Karaf commands: `bundle:install` and `feature:install` (and related ones e.g. `feature:repo-add`, ...).

I hope you understand that this here is for developers that would like to report an issue / bug and not s support forum.
At least `smarthome-packaging-sample-karaf` could be seen as a starting point for developers that would like to create a custom distribution and not as a product to be used for an end user.

**Comment by maggu2810** [comment]
Please close the issue next time yourself.

**Comment by kirantpatil** [comment]
Yes, thank you.

**Comment by kirantpatil** [comment]
I copied the below jar file in **"deploy"** directory as below.

~/smarthome-packaging-sample-karaf/target/assembly/deploy$ ls
org.openhab.ui.dashboard-2.0.0.b3.jar
org.openhab.ui.habpanel-2.1.0-SNAPSHOT.jar
README

Now it shows "Active" in bundle:list as below.

#### karaf@root()> bundle:list
#### START LEVEL 100 , List Threshold: 50
### ID | State     | Lvl | Version               | Name
--------------------------------------------------------------------------------------------------
  9 | Active    |  80 | 2.3.0.201506221200    | JAX-RS Gson Provider
 10 | Active    |  80 | 5.3.1.201602281253    | OSGi JAX-RS Connector
...
...
206 | Active    |  80 | 2.1.0.201701300723    | HABPanel User Interface
207 | Active    |  80 | 2.0.0.b3              | openHAB Dashboard UI

Thanks.

**Comment by maggu2810** [comment]
👍
