### ISSUE TITLE
how to do smarthome packaging with  karaf 

### ISSUE THREAD

**Issue by amarpulli544** [maggu2810/smarthome-packaging-sample-karaf#6]
Hello @maggu2810 ,

I would like to know how to do the smart home packaging with karaf features.
 Please share your steps , which has been done in smart home packaging with karaf.

Thanks and Regards,
Amar.

**Comment by maggu2810** [comment]
Hi @amarpulli544,
I don't like to be harsh, but this is a issue tracker and for bugs.
Please don't use it for support requests.

So, is there any issue?

If you need to learn about Karaf features, you should have a look at the Karaf documentation and the user mailing list for Karaf (but use it if you have question about the general concept, not about ESH related stuff).

If you need to learn about ESH bundles etc. you could use the ESH forum.

If you need to find some examples for packaging and featues, you can have a look at e.g. openHAB.

**Comment by amarpulli544** [comment]
@maggu2810 ,
I am new to Eclipse Smart Home world. 
I want to learn all these things like packaging, and karaf.
I did referred karaf documentation but didn't get clarity about on it..

**Comment by maggu2810** [comment]
Perhaps you can learn something about Karaf using this tutorial:
http://www.liquid-reality.de/display/liquid/Karaf+Tutorials
